version: "3"
services:
  authorization:
    context: ./
    dockerfile: Dockerfile_Auth

  communication:
    context: ./
    dockerfile: Dockerfile_Comm

  config-server:
    context: ./
    dockerfile: Dockerfile_Config_Server

  eureka-server:
    context: ./
    dockerfile: Dockerfile_Eureka_Server

  zuul-server:
    context: ./
    dockerfile: Dockerfile_Zuul_Server